// packages/react/src/Button/Button.tsx
import type { AnchorHTMLAttributes, ButtonHTMLAttributes } from 'react';
import { cn } from '../utils.js';

export type ButtonVariant =
    | 'default'
    | 'secondary'
    | 'destructive'
    | 'outline'
    | 'ghost'
    | 'icon'
    | 'link'
    | 'close';

export type ButtonSize = 'default' | 'sm';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
    variant?: ButtonVariant;
    size?: ButtonSize;
}

export function Button({ variant = 'default', size, className, children, ...props }: ButtonProps) {
    return (
        <button
            className={cn('btn', `btn-${variant}`, size === 'sm' && 'btn-sm', className)}
            {...props}
        >
            {children}
        </button>
    );
}

export interface ButtonLinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
    variant?: ButtonVariant;
    size?: ButtonSize;
}

export function ButtonLink({ variant = 'link', size, className, children, ...props }: ButtonLinkProps) {
    return (
        <a className={cn('btn', `btn-${variant}`, size === 'sm' && 'btn-sm', className)} {...props}>
            {children}
        </a>
    );
}

// packages/vue/src/Button/Button.vue
<script setup lang="ts">
defineProps<{
    variant?: 'default' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'icon' | 'link' | 'close';
    size?: 'default' | 'sm';
    type?: 'button' | 'submit' | 'reset';
    disabled?: boolean;
}>();
</script>

<template>
    <button
        :type="type ?? 'button'"
        :class="['btn', `btn-${variant ?? 'default'}`, size === 'sm' && 'btn-sm']"
        :disabled="disabled"
    >
        <slot />
    </button>
</template>
